### ISSUE TITLE
Error in generating traning_data_generation and model_training, request for code update

### ISSUE THREAD

**Issue by xianghongxu** [wurenzhi/learned_ndv_estimator#1]
Hi, I follow the readme page to generate training data but I found that I can not save `f_s_list` due to a data shape problem. I changed two parameters to obtain quick example results. My numpy version is 1.24.0 and the error that occurs in training_data_generation is shown as follows:
![image](https://github.com/wurenzhi/learned_ndv_estimator/assets/129390699/164b1194-86f7-4309-b45e-9737e5f6cc3c)

Besides, I found there is a bug in model_training that blocks the training loop, https://github.com/wurenzhi/learned_ndv_estimator/blob/9a687d8f0c625b30367051e690c4161424d2f902/model_training/model_training.py#L55. Line 55 declares three parameters for class `ndvDatasetSparse` but Line 80 does not provide the third parameter. https://github.com/wurenzhi/learned_ndv_estimator/blob/9a687d8f0c625b30367051e690c4161424d2f902/model_training/model_training.py#L80

These two problems make generating training data and training the model not available. Could you please update the code when you are free, thank you very much.

**Comment by wurenzhi** [comment]
Hi, thanks for pointing out the issues. I have just submitted a fix. Please have a try now.
